### ISSUE TITLE
BE: Postituse valideerimise testid

### ISSUE THREAD

**Issue by mariliisaar** [rakenduste-programmeerimine-2021/yet-another-dead-forum#47]

**Comment by Uptaker** [comment]
Testing exceptions that are handled by Spring itself with MockMvc seems to be a lot more complex than originally thought.

I'll look into this issue more in the future, but the complexity of the issue and time constraints limit my ability to implement this properly.

See https://github.com/spring-projects/spring-boot/issues/7321 for more information.
